services:
  proxy:
    image: itzg/mc-proxy:latest
    ports:
      - "25565:25565"
      - "25568:25568"
      - "24454:24454/udp"
    environment:
      TYPE: VELOCITY
      MINECRAFT_VERSION: 1.21.10
    volumes:
      - ./velocity_data:/server/
    networks:
      - katcraft_net
    restart: unless-stopped

  katcraftpanel:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: katcraftpanel
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./servers:/app/servers
      - ./velocity_data:/app/velocity_data
      - ./secrets:/app/secrets:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - katcraft_net
      - traefik_default
    restart: unless-stopped
    depends_on:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.katcraftpanel.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.katcraftpanel.loadbalancer.server.port=3000"

networks:
  katcraft_net:
    driver: bridge
    name: katcraft_net
  traefik_default:
    external: true
