const fs = require('fs');
const path = require('path');
const TOML = require('@iarna/toml');
const crypto = require('crypto');

/**
 * Service pour mettre à jour les fichiers de configuration Minecraft
 * après la création/modification d'un serveur
 */
class ConfigUpdater {
  constructor() {
    this.SERVERS_PATH = '/app/servers';
    this.VELOCITY_DATA_PATH = '/app/velocity_data';
  }

  /**
   * Obtenir le chemin complet vers les données d'un serveur
   */
  getServerDataPath(serverName) {
    return path.join(this.SERVERS_PATH, serverName);
  }

  /**
   * Récupérer les ports d'un serveur (défaut: 25575 pour RCON, 25565 pour le jeu)
   */
  getServerPorts(defaults = {}) {
    return {
      rconPort: defaults.rconPort || 25575,
      serverPort: defaults.serverPort || 25565
    };
  }

  /**
   * Écrire un fichier de configuration
   */
  writeFile(filePath, content) {
    try {
      const dir = path.dirname(filePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      fs.writeFileSync(filePath, content, 'utf8');
      return true;
    } catch (err) {
      console.error(`[ConfigUpdater] Error writing ${filePath}:`, err.message);
      return false;
    }
  }

  /**
   * Créer server.properties complet
   */
  async createServerProperties(serverName, options) {
    const {
      motd = `KatCraft - ${serverName}`,
      maxPlayers = 20,
      difficulty = '2',
      gameMode = 'SURVIVAL',
      whitelist = '',
      whitelistEnabled = 'false',
      rconPassword = 'minecraft',
      rconPort = 25575,
      serverPort = 25565,
      viewDistance = 10,
      seed = '',
      spawnProtection = 4,
      rconEnabled = 'true',
      rconAccess = '127.0.0.1'
    } = options;

    const gameModeValue = gameMode === 'SURVIVAL' ? 'survival' : 'creative';
    const difficultyValue = { '0': 'peaceful', '1': 'easy', '2': 'normal', '3': 'hard' }[difficulty] || 'normal';
    
    // Gestion de la seed (ne pas écrire si vide)
    const seedLine = seed && seed.trim() ? `level-seed=${seed}` : '# level-seed=';
    const whitelistLine = whitelistEnabled === 'true' ? `whitelist=${whitelist}` : '# whitelist=';

    const template = `#KATCRAFT_CONFIG_MARKER
# Minecraft server properties
# Generated by KatCraftPanel

# Server settings
motd=${motd}
max-players=${maxPlayers}
max-world-size=-1
allow-nether=true
enable-query=false
query.port=25565
enable-whitelist=${whitelistEnabled}
spawn-anchors=true
allow-end=true
spawn-protection=${spawnProtection}
network-compression-threshold=256
online-mode=false
enable-rcon=${rconEnabled}
rcon.password=${rconPassword}
rcon.port=${rconPort}
rcon.access=${rconAccess}
game-mode=${gameModeValue}
difficulty=${difficultyValue}
spawn-monsters=true
gamemode=survival
pvp=true
spawn-radius=8
view-distance=${viewDistance}
server-port=${serverPort}
server-ip=
default-game-mode=survival
prevent-proxy-connections=false
enable-command-block=false
enable-default-ops=true
generator-settings=
level-name=world
level-type=minecraft:overworld
${seedLine}
player-idle-timeout=0
rate-limit=0
${whitelistLine}
server-port IPv6=0
allow-flight=false
announce-achievements=true
resource-pack=
resource-pack-sha1=
network-compression-threshold=256
max-build-height=256
min-edition-version=
server-backup-dir=
max-tick-time=60000
enable-one-tick-worlds=false
server.properties.encoding=

#KATCRAFT_CONFIG_MARKER
`;

    return await this.writeFile(
      path.join(this.getServerDataPath(serverName), 'server.properties'),
      template
    );
  }

  /**
   * Créer ops.json
   */
  createOpsJson(serverName, opsList) {
    try {
      const ops = [];
      if (opsList && opsList.trim()) {
        opsList.split(',').forEach(op => {
          const name = op.trim();
          if (name) {
            // Générer un UUID virtuel pour l'UUID
            const uuid = crypto.createHash('md5').update(name).digest('hex');
            ops.push({
              uuid: `${uuid.substring(0,8)}-${uuid.substring(8,12)}-${uuid.substring(12,16)}-${uuid.substring(16,20)}-${uuid.substring(20,32)}`,
              name: name,
              level: 4
            });
          }
        });
      }

      const opsJson = JSON.stringify(ops, null, 2);
      return this.writeFile(
        path.join(this.getServerDataPath(serverName), 'ops.json'),
        opsJson
      );
    } catch (err) {
      console.error('[ConfigUpdater] Error creating ops.json:', err.message);
      return false;
    }
  }

  /**
   * Créer whitelist.json
   */
  createWhitelistJson(serverName, whitelistList) {
    try {
      const whitelist = [];
      if (whitelistList && whitelistList.trim()) {
        whitelistList.split(',').forEach(player => {
          const name = player.trim();
          if (name) {
            // Générer un UUID virtuel pour l'UUID
            const uuid = crypto.createHash('md5').update(name).digest('hex');
            whitelist.push({
              uuid: `${uuid.substring(0,8)}-${uuid.substring(8,12)}-${uuid.substring(12,16)}-${uuid.substring(16,20)}-${uuid.substring(20,32)}`,
              name: name
            });
          }
        });
      }

      const whitelistJson = JSON.stringify(whitelist, null, 2);
      return this.writeFile(
        path.join(this.getServerDataPath(serverName), 'whitelist.json'),
        whitelistJson
      );
    } catch (err) {
      console.error('[ConfigUpdater] Error creating whitelist.json:', err.message);
      return false;
    }
  }

  /**
   * Activer/désactiver whitelist
   */
  enableWhitelist(serverName, enabled) {
    try {
      const content = enabled ? '' : '# whitelist=disabled';
      this.writeFile(
        path.join(this.getServerDataPath(serverName), 'whitelist.txt'),
        content
      );
      return true;
    } catch (err) {
      console.error('[ConfigUpdater] Error creating whitelist.txt:', err.message);
      return false;
    }
  }

  /**
   * Créer bstats.xml pour Paper/Spigot
   */
  createBStatsXml(serverName, enabled) {
    try {
      const content = `<?xml version="1.0" encoding="UTF-8"?>
<bStats>
  <plugin>
    <name>KatCraftPanel</name>
    <id>katcraftpanel</id>
    <value>${enabled ? 'true' : 'false'}</value>
  </plugin>
</bStats>`;
      return this.writeFile(
        path.join(this.getServerDataPath(serverName), 'bstats.xml'),
        content
      );
    } catch (err) {
      console.error('[ConfigUpdater] Error creating bstats.xml:', err.message);
      return false;
    }
  }

  /**
   * Mettre à jour tous les fichiers de configuration pour un serveur
   */
  async updateServerConfig(serverName, options) {
    const results = {
      serverProperties: false,
      opsJson: false,
      whitelistJson: false,
      enableWhitelist: false,
      bstatsXml: false
    };

    // Utiliser les ports explicites ou des valeurs par défaut
    const defaults = {
      rconPort: options.rconPort,
      serverPort: options.serverPort
    };
    const ports = this.getServerPorts(defaults);

    // Créer server.properties
    results.serverProperties = await this.createServerProperties(serverName, {
      motd: options.motd || `KatCraft - ${serverName}`,
      maxPlayers: options.maxPlayers || 20,
      difficulty: options.difficulty || '2',
      gameMode: options.mode || 'SURVIVAL',
      whitelist: options.whitelist || '',
      whitelistEnabled: String(options.enableWhitelist || false),
      rconPassword: options.rconPassword || 'minecraft',
      rconPort: ports.rconPort,
      serverPort: ports.serverPort,
      viewDistance: options.viewDistance || 10,
      seed: options.seed || '',
      spawnProtection: options.spawnProtection || 4,
      rconEnabled: String(options.enableRcon || true)
    });

    // Créer ops.json
    if (options.ops) {
      results.opsJson = this.createOpsJson(serverName, options.ops);
    }

    // Créer whitelist.json
    if (options.enableWhitelist) {
      results.whitelistJson = this.createWhitelistJson(serverName, options.whitelist);
      results.enableWhitelist = this.enableWhitelist(serverName, true);
    }

    // Créer bstats.xml
    results.bstatsXml = this.createBStatsXml(serverName, true);

    return results;
  }

  /**
   * Mettre à jour velocity.toml
   */
  updateVelocityConfig() {
    const velocityService = require('./velocity');
    return velocityService.readVelocityConfig() !== null;
  }

  /**
   * Mettre à jour autoserver config
   */
  updateAutoServerConfig(serverName, options) {
    const autoserverService = require('./autoserver');
    return autoserverService.addServerToAutoServer(serverName, {
      startupDelay: options.startupDelay || 30,
      shutdownDelay: options.shutdownDelay || 10,
      autoShutdownDelay: options.autoShutdownDelay || 600
    });
  }

  /**
   * Mettre à jour toutes les configurations
   * options doit contenir: rconPort, serverPort (requis)
   */
  async updateAllConfig(serverName, options = {}) {
    const results = {};

    results.serverConfig = await this.updateServerConfig(serverName, options);
    results.velocity = this.updateVelocityConfig();
    results.autoserver = this.updateAutoServerConfig(serverName, {
      startupDelay: options.startupDelay,
      shutdownDelay: options.shutdownDelay,
      autoShutdownDelay: options.autoShutdownDelay
    });

    return results;
  }
}

module.exports = new ConfigUpdater();
